# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2bc89011599aa12d99e9527e0e9796191d6b826790c23f3cc6eeaf6846a3127f2a882b081cb46f121fd6937fddd55186c68c148f5496ba62d31191bc836ac58

test:
  secret_key_base: 34b8c2166b5a5f10879f07a9364037c340cf7a4fc5c3758a892b0050402c1e708cd9a15b6340efbc55f1e4620de605e8be74378b2eba9a7b98943690290c45c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
